### ISSUE TITLE
money.exceptions.InvalidOperandError: Invalid operand types for operation

### ISSUE THREAD

**Issue by francesco1119** [vimeo/py-money#4]
I have my spare code:

```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from money.money import Money
from money.currency import Currency							
x = Money('0.01', Currency.GBP)

words = 'alphabet'

for i in words:
	x += 0.01

print (x)
```
But when I run it it returns me:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    x += 0.01
  File "C:\Program Files\Python36\lib\site-packages\money\money.py", line 81, in __add__
    raise InvalidOperandError
money.exceptions.InvalidOperandError: Invalid operand types for operation
```
I believe `+=` is the problem

**Comment by nickyr** [comment]
The problem is that you are trying to add a float to a Money, but you must add a Money to a Money. Additionally, the Currencies of the two Monies must match. So you should use:

```python
x += Money('0.01', Currency.GBP)
```
